### ISSUE TITLE
Fix repo url after pol-is => compdemocracy

### ISSUE THREAD

**Issue by patcon** [compdemocracy/polis-examples#4]
Current url under repo description: https://pol-is.github.io/polis-examples/

Should be: https://compdemocracy.github.io/polis-examples/

🙌 🙌 🙌 🙌 🙌

**Comment by patcon** [comment]
@metasoarous was reminded of this by https://github.com/compdemocracy/polis/issues/964#issuecomment-898753043

Any chance we could edit the link on this repo to point correctly to https://compdemocracy.github.io/polis-examples/ ? Thanks!

**Comment by metasoarous** [comment]
Thanks for catching this; Done.

Obviously, we should probably merge this repository with https://github.com/compdemocracy/polis-embed-example, but given that the methods illustrated here aren't all functional at the moment, don't want to confuse things.
